matrix:
  include:
    - language: php
      sudo: false
      php: 7.4
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install
      script:
        - composer run-script phpunit:ci
    - language: php
      sudo: false
      php: 8.0
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install
      script:
        - composer run-script phpunit:ci
        - composer run-script phpcs:ci
      after_success:
        - travis_retry php vendor/bin/php-coveralls
